# Generated by Django 5.0.6 on 2024-06-10 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id_pelicula', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('director', models.CharField(verbose_name='Director')),
                ('anio', models.CharField(verbose_name='Año')),
                ('sinopsis', models.CharField(verbose_name='Sinopsis')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('genero', models.CharField(verbose_name='Género')),
                ('duracion', models.CharField(verbose_name='Duración')),
                ('imagen', models.ImageField(blank=True, default='movie-cover', null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de crédito/débito'), ('transferencia', 'Transferencia bancaria')])),
                ('numero_tarjeta', models.CharField(max_length=16, null=True, verbose_name='Numero tarjeta')),
                ('peliculas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.CharField(unique=True, verbose_name='Email')),
                ('usuario', models.CharField(unique=True, verbose_name='Usuario')),
                ('contrasenia', models.CharField(unique=True, verbose_name='Contraseña')),
                ('lista_peliculas', models.ManyToManyField(through='web.Transaccion', to='web.pelicula')),
            ],
        ),
        migrations.AddField(
            model_name='transaccion',
            name='usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='transaccion',
            unique_together={('usuarios', 'peliculas')},
        ),
    ]
