# Generated by Django 5.0.6 on 2024-06-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id_pelicula', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('director', models.CharField(verbose_name='Director')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('sinopsis', models.CharField(verbose_name='Sinopsis')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('genero', models.CharField(verbose_name='Género')),
                ('duracion', models.CharField(verbose_name='Duración')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
