# Generated by Django 4.2.8 on 2024-06-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='medio_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de crédito'), ('tarjeta', 'Tarjeta de débito')]),
        ),
    ]
