# Generated by Django 4.2.8 on 2024-06-22 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_transaccion_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='peliculas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_movies', to='web.pelicula'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usuario'),
        ),
    ]
