# Generated by Django 5.0.6 on 2024-06-06 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_pelicula_anio_alter_pelicula_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_pago', models.CharField(verbose_name='Medio de pago')),
                ('fecha', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha')),
                ('id_pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.CharField(unique=True, verbose_name='Email')),
                ('usuario', models.CharField(unique=True, verbose_name='Usuario')),
                ('contrasenia', models.CharField(unique=True, verbose_name='Contraseña')),
                ('lista_peliculas', models.ManyToManyField(through='web.Transaccion', to='web.pelicula')),
            ],
        ),
        migrations.AddField(
            model_name='transaccion',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='transaccion',
            unique_together={('id_usuario', 'id_pelicula')},
        ),
    ]
